version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  deploy:
    docker:
      - image: circleci/node:16.3.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "setup"
          command: 'git config user.email "francois_vd@icloud.com" && git config user.name "フランソワ"'
      - run:
          name: 'deploy'
          command: npm run deploy
  test:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: 'test'
          command: npm run test

workflows:
  version: 2
  run-tests:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
