//Box Icons (https://boxicons.com/)
export { default as arrange } from './paths/arrange.json'
export { default as coffee } from './paths/coffee.json'
export { default as drop } from './paths/drop.json'
export { default as email } from './paths/email.json'
export { default as github } from './paths/github.json'
export { default as gitlab } from './paths/gitlab.json'
export { default as graduation } from './paths/graduation.json'
export { default as helping } from './paths/helping.json'
export { default as linkedin_square } from './paths/linkedin-square.json'
export { default as linkedin } from './paths/linkedin.json'
export { default as stackoverflow } from './paths/stackoverflow.json'
export { default as threads } from './paths/threads.json'
export { default as trophy } from './paths/trophy.json'
